export const SPEC_INTENT_FIELD_MAP = Object.freeze({
  summary: '한 줄 요약',
  problemFrame: '문제정의_5가지',
  who: '누가',
  when: '언제',
  what: '무엇을',
  why: '왜',
  success: '성공기준',
  roles: '사용자역할',
  role: '역할',
  description: '설명',
  features: '핵심_기능',
  must: '필수',
  nice: '있으면 좋음',
  inputFields: '입력_데이터_필드',
  name: '이름',
  type: '타입',
  example: '예시',
  permissions: '권한_규칙',
  read: '조회',
  create: '생성',
  update: '수정',
  delete: '삭제',
  notes: '비고',
  ambiguities: '남은_모호함',
  missing: '부족한_정보',
  questions: '확인_질문_3개',
  risks: '리스크_주의점_3개',
});
